import { AlertOctagon, AlertTriangle, Info, RefreshCw, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import type { Insight, InsightSeverity } from "../../types";
import { RISK_COLORS } from "../charts/theme";

const SEVERITY_CONFIG: Record<InsightSeverity, { color: string; icon: typeof AlertOctagon; label: string }> = {
  critical: { color: RISK_COLORS.critical, icon: AlertOctagon, label: "Critical" },
  high: { color: RISK_COLORS.high, icon: AlertTriangle, label: "High" },
  medium: { color: RISK_COLORS.medium, icon: AlertTriangle, label: "Medium" },
  info: { color: "#2a78d6", icon: Info, label: "Info" },
};

interface AiInsightsPanelProps {
  insights: Insight[];
  loading: boolean;
  onRefresh: () => void;
}

export default function AiInsightsPanel({ insights, loading, onRefresh }: AiInsightsPanelProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const usedAi = insights.some((i) => i.generatedBy === "ai");

  return (
    <section id="ai-insights" data-tour="ai-insights" className="bg-surface border border-ink-primary/10 rounded-2xl p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-chart-5/15 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-chart-5" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-ink-primary">AI Proactive Insights</h2>
            <p className="text-xs text-ink-muted">
              {usedAi ? "Generated by Claude from live provider metrics" : "Rule-based analysis (offline mode)"}
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={onRefresh}
          disabled={loading}
          className="flex items-center gap-1.5 text-xs text-ink-secondary border border-line-axis rounded-lg px-3 py-1.5 hover:bg-plane transition disabled:opacity-50"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {loading && insights.length === 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-28 rounded-xl bg-plane animate-pulse" />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {insights.map((insight) => {
            const config = SEVERITY_CONFIG[insight.severity];
            const Icon = config.icon;
            const impact = insight.estimatedFinancialImpact ?? 0;
            return (
              <div
                key={insight.id}
                className="rounded-xl border border-line-grid p-4 flex flex-col gap-2 hover:border-ink-primary/20 transition"
              >
                <div className="flex items-center justify-between">
                  <span
                    className="inline-flex items-center gap-1.5 text-xs font-medium px-2 py-0.5 rounded-full"
                    style={{ backgroundColor: `${config.color}1a`, color: config.color }}
                  >
                    <Icon className="w-3 h-3" />
                    {config.label}
                  </span>
                  <span className="text-xs text-ink-muted tabular-nums">
                    {Math.round(insight.confidenceScore * 100)}% confidence
                  </span>
                </div>
                <h3 className="text-sm font-medium text-ink-primary">{insight.title}</h3>
                <p className="text-xs text-ink-secondary leading-relaxed">{insight.narrative}</p>
                {insight.recommendedAction && (
                  <p className="text-xs text-chart-1 leading-relaxed">→ {insight.recommendedAction}</p>
                )}
                <div className="flex items-center justify-between mt-auto pt-2 border-t border-line-grid">
                  <div className="flex items-center gap-1 text-xs tabular-nums">
                    {impact !== 0 && (
                      <>
                        {impact > 0 ? (
                          <TrendingUp className="w-3.5 h-3.5 text-risk-low" />
                        ) : (
                          <TrendingDown className="w-3.5 h-3.5 text-risk-critical" />
                        )}
                        <span className={impact > 0 ? "text-risk-low" : "text-risk-critical"}>
                          ${Math.abs(impact).toLocaleString()}
                        </span>
                      </>
                    )}
                  </div>
                  {insight.providerId && (
                    <button
                      type="button"
                      onClick={() => navigate(`/providers/${insight.providerId}`, { state: { backgroundLocation: location } })}
                      className="text-xs font-medium text-chart-1 hover:underline"
                    >
                      View provider →
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
